<robot name="my_camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="camera_length" value="0.01"/> <!--摄像头长-->
    <xacro:property name="camera_width" value="0.025"/> <!--摄像头宽-->
    <xacro:property name="camera_height" value="0.025"/> <!--摄像头高-->
    <xacro:property name="camera_x" value="0.08"/> <!--摄像头x-->
    <xacro:property name="camera_y" value="0"/> <!--摄像头y-->
    <xacro:property name="camera_z" value="${camera_height/2+base_link_length/2}"/> <!--摄像头z-->
    <!--摄像头关节-->
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="black" />
         </visual>
    </link>
    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_x} ${camera_y} ${camera_z}"/>
    </joint>
</robot>
